---
title: "Final Project"
author: "Team"
date: "December 7, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cities}
require(jsonlite) #we will be loading a JSON file from the web
cities.url <- "https://www.numbeo.com/api//cities?api_key=vjd4t3rcp6nc50&country=United%20States"
api.key <- "&api_key=vjd4t3rcp6nc50"
cities <- data.frame(fromJSON(paste0(cities.url, api.key)))
colnames(cities) <- c("Country", "City", "Latitude", "City ID", "Longitude")
View(cities)
```

```{r price items}
priceitems.url <- "https://www.numbeo.com/api/price_items?"
api.key <- "&api_key=vjd4t3rcp6nc50"
price.items <- data.frame(fromJSON(paste0(priceitems.url, api.key)), simplifyDataFrame= TRUE)
View(price.items)

```

```{r city prices}
cityprices.url <- ""
```

```{r historical city prices}
#I think this needs to be done once we've narrowed down our cities
```

```{r city prices raw}
#I think this needs to be done once we've narrowed down our cities
```

```{r country traffic}
counttraf.url <- "https://www.numbeo.com/api/country_traffic?"
api.key <- "&api_key=vjd4t3rcp6nc50"
country.traffic <- data.frame(fromJSON(paste0(counttraf.url, api.key)))
View(country.traffic)
```


```{r}
pollution.url <- "https://www.numbeo.com/api/country_pollution?"
country.pollution <- fromJSON(paste0(pollution.url, api.key))
require(reshape2)
country.pollution <- rownames(country.pollution) 
melt(country.pollution, na.rm = FALSE, value.name = "value")
View(country.pollution)
```

